allowBuilds:
  esbuild: true
  lightningcss: true

overrides:
  "@codemirror/state": "6.7.4"
  "@codemirror/view": "6.43.11"
  "@codemirror/language": "6.12.4"
  "@codemirror/commands": "6.11.0"
  "@codemirror/autocomplete": "6.20.3"
  "@codemirror/lint": "6.9.7"
