/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsRouteRouteImport } from './routes/_tools/route'
import { Route as ToolsDecoRouteImport } from './routes/_tools/deco'
import { Route as ToolsDiffCheckerRouteImport } from './routes/_tools/diff-checker'
import { Route as ToolsImageEditorRouteImport } from './routes/_tools/image-editor'
import { Route as ToolsNameCheckerRouteImport } from './routes/_tools/name-checker'
import { Route as ToolsPdfEditorRouteImport } from './routes/_tools/pdf-editor'
import { Route as ToolsQrCodeRouteImport } from './routes/_tools/qr-code'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ApiCheckDomainRouteImport } from './routes/api/check-domain'
import { Route as ApiCheckPlatformRouteImport } from './routes/api/check-platform'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRouteRoute = ToolsRouteRouteImport.update({
  id: '/_tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDecoRoute = ToolsDecoRouteImport.update({
  id: '/deco',
  path: '/deco',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsDiffCheckerRoute = ToolsDiffCheckerRouteImport.update({
  id: '/diff-checker',
  path: '/diff-checker',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsImageEditorRoute = ToolsImageEditorRouteImport.update({
  id: '/image-editor',
  path: '/image-editor',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsNameCheckerRoute = ToolsNameCheckerRouteImport.update({
  id: '/name-checker',
  path: '/name-checker',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsPdfEditorRoute = ToolsPdfEditorRouteImport.update({
  id: '/pdf-editor',
  path: '/pdf-editor',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsQrCodeRoute = ToolsQrCodeRouteImport.update({
  id: '/qr-code',
  path: '/qr-code',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckDomainRoute = ApiCheckDomainRouteImport.update({
  id: '/api/check-domain',
  path: '/api/check-domain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckPlatformRoute = ApiCheckPlatformRouteImport.update({
  id: '/api/check-platform',
  path: '/api/check-platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deco': typeof ToolsDecoRoute
  '/diff-checker': typeof ToolsDiffCheckerRoute
  '/image-editor': typeof ToolsImageEditorRoute
  '/name-checker': typeof ToolsNameCheckerRoute
  '/pdf-editor': typeof ToolsPdfEditorRoute
  '/qr-code': typeof ToolsQrCodeRoute
  '/api/$': typeof ApiSplatRoute
  '/api/check-domain': typeof ApiCheckDomainRoute
  '/api/check-platform': typeof ApiCheckPlatformRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deco': typeof ToolsDecoRoute
  '/diff-checker': typeof ToolsDiffCheckerRoute
  '/image-editor': typeof ToolsImageEditorRoute
  '/name-checker': typeof ToolsNameCheckerRoute
  '/pdf-editor': typeof ToolsPdfEditorRoute
  '/qr-code': typeof ToolsQrCodeRoute
  '/api/$': typeof ApiSplatRoute
  '/api/check-domain': typeof ApiCheckDomainRoute
  '/api/check-platform': typeof ApiCheckPlatformRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tools': typeof ToolsRouteRouteWithChildren
  '/_tools/deco': typeof ToolsDecoRoute
  '/_tools/diff-checker': typeof ToolsDiffCheckerRoute
  '/_tools/image-editor': typeof ToolsImageEditorRoute
  '/_tools/name-checker': typeof ToolsNameCheckerRoute
  '/_tools/pdf-editor': typeof ToolsPdfEditorRoute
  '/_tools/qr-code': typeof ToolsQrCodeRoute
  '/api/$': typeof ApiSplatRoute
  '/api/check-domain': typeof ApiCheckDomainRoute
  '/api/check-platform': typeof ApiCheckPlatformRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deco'
    | '/diff-checker'
    | '/image-editor'
    | '/name-checker'
    | '/pdf-editor'
    | '/qr-code'
    | '/api/$'
    | '/api/check-domain'
    | '/api/check-platform'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deco'
    | '/diff-checker'
    | '/image-editor'
    | '/name-checker'
    | '/pdf-editor'
    | '/qr-code'
    | '/api/$'
    | '/api/check-domain'
    | '/api/check-platform'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/_tools'
    | '/_tools/deco'
    | '/_tools/diff-checker'
    | '/_tools/image-editor'
    | '/_tools/name-checker'
    | '/_tools/pdf-editor'
    | '/_tools/qr-code'
    | '/api/$'
    | '/api/check-domain'
    | '/api/check-platform'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsRouteRoute: typeof ToolsRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiCheckDomainRoute: typeof ApiCheckDomainRoute
  ApiCheckPlatformRoute: typeof ApiCheckPlatformRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tools': {
      id: '/_tools'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ToolsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tools/deco': {
      id: '/_tools/deco'
      path: '/deco'
      fullPath: '/deco'
      preLoaderRoute: typeof ToolsDecoRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/diff-checker': {
      id: '/_tools/diff-checker'
      path: '/diff-checker'
      fullPath: '/diff-checker'
      preLoaderRoute: typeof ToolsDiffCheckerRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/image-editor': {
      id: '/_tools/image-editor'
      path: '/image-editor'
      fullPath: '/image-editor'
      preLoaderRoute: typeof ToolsImageEditorRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/name-checker': {
      id: '/_tools/name-checker'
      path: '/name-checker'
      fullPath: '/name-checker'
      preLoaderRoute: typeof ToolsNameCheckerRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/pdf-editor': {
      id: '/_tools/pdf-editor'
      path: '/pdf-editor'
      fullPath: '/pdf-editor'
      preLoaderRoute: typeof ToolsPdfEditorRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/_tools/qr-code': {
      id: '/_tools/qr-code'
      path: '/qr-code'
      fullPath: '/qr-code'
      preLoaderRoute: typeof ToolsQrCodeRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-domain': {
      id: '/api/check-domain'
      path: '/api/check-domain'
      fullPath: '/api/check-domain'
      preLoaderRoute: typeof ApiCheckDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-platform': {
      id: '/api/check-platform'
      path: '/api/check-platform'
      fullPath: '/api/check-platform'
      preLoaderRoute: typeof ApiCheckPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ToolsRouteRouteChildren {
  ToolsDecoRoute: typeof ToolsDecoRoute
  ToolsDiffCheckerRoute: typeof ToolsDiffCheckerRoute
  ToolsImageEditorRoute: typeof ToolsImageEditorRoute
  ToolsNameCheckerRoute: typeof ToolsNameCheckerRoute
  ToolsPdfEditorRoute: typeof ToolsPdfEditorRoute
  ToolsQrCodeRoute: typeof ToolsQrCodeRoute
}

const ToolsRouteRouteChildren: ToolsRouteRouteChildren = {
  ToolsDecoRoute: ToolsDecoRoute,
  ToolsDiffCheckerRoute: ToolsDiffCheckerRoute,
  ToolsImageEditorRoute: ToolsImageEditorRoute,
  ToolsNameCheckerRoute: ToolsNameCheckerRoute,
  ToolsPdfEditorRoute: ToolsPdfEditorRoute,
  ToolsQrCodeRoute: ToolsQrCodeRoute,
}

const ToolsRouteRouteWithChildren = ToolsRouteRoute._addFileChildren(
  ToolsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsRouteRoute: ToolsRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiCheckDomainRoute: ApiCheckDomainRoute,
  ApiCheckPlatformRoute: ApiCheckPlatformRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
